logmanagersrv       [d]
bindermanagersrv    [d]
mediatorsrv         [d] [argv: --heartbeat=on]
propertiessrv       [d] [argv: --heartbeat=on]
configmanagersrv    [d] [argv: --heartbeat=on]
powermanagersrv     [d] [argv: --heartbeat=on]
sparrowsrv          [d] [argv: --heartbeat=on]
statusmonitorsrv        [argv: --heartbeat=on]
