[output.default]                        # 默认输出
frame_length_bytes  = 1024              # 单条日志帧最大长度，单位：字节
enabled             = true              # 是否启用日志输出
level               = debug             # 日志级别：error、warn、info、debug
output              = file              # 输出方式：file、stdout
file_path           = /tmp/sprlog/main  # 日志目录
file_name           = main.log          # 日志文件名
file_name_format    = BN_ST.FX          # 日志文件名格式: BN：基础名称，FX：文件扩展名，ST：本地时间戳，SI: 系统启动短标识，MH: 进程单调时间戳
file_num            = 10                # 保留日志文件数量
file_capacity_mb    = 10                # 单个日志文件最大容量，单位：MB
flush_count         = 64                # 累积日志条数达到该值时刷新
flush_interval_ms   = 1000              # 定时刷新间隔，单位：毫秒

# [output.test_internal]
# file_path           = /tmp/sprlog/testinternal
# file_name           = testinternal.log
# file_capacity_mb    = 10
# flush_count         = 32
# flush_interval_ms   = 500

# [output.test_benchmark]
# file_path           = /tmp/sprlog/testbenchmark
# file_name           = testbenchmark.log
# file_capacity_mb    = 10
# flush_count         = 32
# flush_interval_ms   = 500

