# OneNet Device Configuration
[Device_PC_TEST_01]
ExpirationTime=1880935253
OneDevName=PC_TEST_01
OneProductID=j9hPuM1K23
OneKey=UWdxM1lMa3ZuZ25xVWhqdFp3dDl4VTNtYU5scERlM2o=
OneToken=version=2018-10-31&res=products%2Fj9hPuM1K23%2Fdevices%2FPC_TEST_01&et=1880935253&method=md5&sign=EPOJVwz3SqvyHlngxavWOQ%3D%3D

[Device_PC_TEST_02]
ExpirationTime=1880935253
OneDevName=PC_TEST_02
OneProductID=j9hPuM1K23
OneKey=MWpTVWFNSkZCRzh5WHRZNXhnZEVCeW9zcnd6cEZndzE==
OneToken=version=2018-10-31&res=products%2Fj9hPuM1K23%2Fdevices%2FPC_TEST_02&et=1880935253&method=md5&sign=752DXcCkSCVeeSa6VkdIZw%3D%3D
